### PR TITLE
Make chimera_load_ui_map load the main menu too

### PR DESCRIPTION
**Pull request by JerryBrick**
Hey Kava, this is what I was talking about. I also have a question, is call the function from ASM better than just reinterpret the pointer using reinterpret_cast? I'm curious about that.

PS: thanks to Sledmine for finding the function to load the main menu.

### CODE REVIEW

**Comment by Kavawuvi** [comment]
I've found that a lot of times, the underlying function can mangle registers, or it requires certain registers to be set to certain values, as Halo passes some things by registers. I don't know why it does what it does, but it does. Using pushad/pushfd can protect this from occurring.

Calling the functions directly in C/C++ doesn't offer such protections.

**Comment by Kavawuvi** [comment]
I've found that a lot of times, the underlying function can mangle registers, or it requires certain registers to be set to certain values, as Halo passes some things by registers. I don't know why it does what it does (performance maybe?), but it does. Using pushad/pushfd can protect this from occurring.

Calling the functions directly in C/C++ doesn't offer such protections.

If you're satisfied, I can merge this.

**Comment by JerryBrick** [comment]
Thanks! that explains a lot of things

**Comment by Kavawuvi** [comment]
Merged!

**Pull request merged**
