### PR TITLE
Widescreen tweaks and Interpolation bug fix

### PR DESCRIPTION
**Pull request by JerryBrick**
Hey Kava, maybe this could be useful.

**Changes**:
- Changed the UI widget resizing condition (lol). 
Before: https://i.imgur.com/rQZ0Ccb.png | After: https://i.imgur.com/yTvnLrz.png

- Decreased centering bounds of the HUD elements in widescreen fix.
Before: https://i.imgur.com/c3RelNV.png | After: https://i.imgur.com/iuYM1CA.png

- Fixed a interpolation bug related to singleplayer pause menu.
https://www.youtube.com/watch?v=w4yvP_BVkNY (sorry for the crappy quality)

### CODE REVIEW

**Comment by Kavawuvi** [comment]
Hello, Jerry. Thanks for your contributions!

You might notice that, when you tweak the widescreen fix, you can fix some maps. However, this can come at the cost of breaking others. For example, the numbers next to "TARGET DISTANCE:" and "TARGET ELEVATION:" in stock maps is broken with your changes.

- Before: https://i.imgur.com/LXhPgvZ.png
- After: https://i.imgur.com/NhEhZDV.png

Unfortunately this is the nature of widescreen fixes, and you'll find that no widescreen fix can truly fit every situation with the large variety of custom HUDs out there. Perhaps this issue should be addressed by implementing some sort of method to define it as a map-by-map basis rather than globally. I'm considering an ini option in that case.

For your other contribution: the pause thing is good and has been needed for a while (I've never really gotten around to it, so thanks!). My only comment on it is that you used a hardcoded address, and the particular address you used is invalid for the demo version of the game. This isn't a problem, as I've found the signature for it, so it can be pretty easily adapted to work on all supported versions.

Again, thanks! I rarely ever get PRs on my projects, so I'm very pleased to respond to yours.

**Comment by JerryBrick** [comment]
Hmm I see, so the best option will be fix that HUD to match with the the current widescreen fix settings.

About the pause menu thing, I'm glad to know that will be useful. I tried to make a signature for the memory address but I couldn't, my knowledge about those stuff is very limited.

I also have a couple of patches for the game that maybe could be in Chimera. Should I open a new pull request (I will be more careful with some details next time haha) or just tell you on the Chimera discord server?

Glad to contribute (in some way) to this project 👍

**Comment by Kavawuvi** [comment]
Yes, of course! If you want to talk with me on the Chimera Discord about this, go ahead.

Anyway, if you can, try putting individual features and enhancements into separate pull requests. I know that might be a bit more work, but it'd be a easier to handle since they can be approved separately rather than all together.

**Comment by Vaporeon** [comment]
Hi, do you mind making the pause fix it's own pull request so it can be merged?

**Comment by JerryBrick** [comment]
Oh yes I forgot, sorry!

**Pull request closed without merging**
